### PR TITLE
fix(bridge): support Unity 6.5 object identifiers

### LINKED ISSUE #231: Unity 6.5 compile error: `Object.GetInstanceID()` is obsolete and should be migrated to `GetEntityId()`
## Summary

`com.akiojin.unity-cli-bridge` fails to compile in Unity 6.5 because several editor-side bridge scripts still call `UnityEngine.Object.GetInstanceID()`.

In Unity 6.5, `Object.GetInstanceID()` is now obsolete and Unity reports it as a CS0619 compile error:

> `Object.GetInstanceID()` is obsolete: `GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.`

Because the bridge package uses `GetInstanceID()` in multiple handlers and helper classes, the Unity project cannot finish compiling after the package is imported.

## Environment

- Unity version: Unity 6.5 / 6000.5.x
- Package: `com.akiojin.unity-cli-bridge`
- Package source/hash shown in PackageCache: `3a41bf6dc060`
- Install method: Unity Package Manager / Git package
- OS: macOS
- Project type: Unity 6.5 project using `akiojin/unity-cli`

## Steps to reproduce

1. Open a Unity 6.5 project.
2. Add `com.akiojin.unity-cli-bridge` from this repository.
3. Let Unity import and compile the package.
4. Check the Unity Console.

## Actual result

Unity compilation fails with CS0619 errors from `unity-cli-bridge`:

```text
Library/PackageCache/com.akiojin.unity-cli-bridge@3a41bf6dc060/Editor/Helpers/RuntimeChangeJournal.cs(39,22): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'

Library/PackageCache/com.akiojin.unity-cli-bridge@3a41bf6dc060/Editor/Handlers/GameObjectHandler.cs(105,26): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'

Library/PackageCache/com.akiojin.unity-cli-bridge@3a41bf6dc060/Editor/Handlers/GameObjectHandler.cs(381,26): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'

Library/PackageCache/com.akiojin.unity-cli-bridge@3a41bf6dc060/Editor/Handlers/GameObjectHandler.cs(468,26): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'

Library/PackageCache/com.akiojin.unity-cli-bridge@3a41bf6dc060/Editor/Handlers/ComponentHandler.cs(2030,30): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'

Library/PackageCache/com.akiojin.unity-cli-bridge@3a41bf6dc060/Editor/Handlers/SceneAnalysisHandler.cs(393,38): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'

Library/PackageCache/com.akiojin.unity-cli-bridge@3a41bf6dc060/Editor/Handlers/SelectionHandler.cs(272,33): error CS0619: 'Object.GetInstanceID()' is obsolete: 'GetInstanceID is deprecated. Use GetEntityId instead. This will be removed in a future version.'
```

## Expected result

The bridge package should compile successfully in Unity 6.5.

## Suspected cause

Unity 6.5 deprecates `UnityEngine.Object.GetInstanceID()` and requires `UnityEngine.Object.GetEntityId()` instead.

The affected bridge code appears to expose or store Unity object identifiers as `int` values returned by `GetInstanceID()`, for example in:

- `RuntimeChangeJournal.cs`
- `GameObjectHandler.cs`
- `ComponentHandler.cs`
- `SceneAnalysisHandler.cs`
- `SelectionHandler.cs`

## Suggested fix

Please consider migrating the bridge from `Object.GetInstanceID()` to `Object.GetEntityId()` for Unity 6.5 compatibility.

A simple `GetEntityId().GetHashCode()` replacement may not be ideal if the value is used as a stable or unique object identifier, because `EntityId` is no longer guaranteed to be representable as a single `int` going forward. It may be safer to:

- use `EntityId` directly internally where possible,
- update response DTOs/protocol fields that currently assume `int id`,
- use `EntityId.None` / validity checks instead of `0`-based instance ID assumptions,
- add conditional compilation if older Unity versions still need to be supported.

For example, the bridge may need a compatibility layer around object identifiers instead of directly returning `GetInstanceID()` from each handler.

## References

- Unity `Object.GetInstanceID()` documentation:  
  https://docs.unity3d.com/ScriptReference/Object.GetInstanceID.html

- Unity `Object.GetEntityId()` documentation:  
  https://docs.unity3d.com/6000.4/Documentation/ScriptReference/Object.GetEntityId.html

- Unity discussion about `GetInstanceID()` / `EntityId` migration:  
  https://discussions.unity.com/t/is-getentityid-gethashcode-a-direct-replacement-for-getinstanceid-if-only-for-the-time-being/1721711

Thank you for maintaining `unity-cli`. This tool is very useful for Unity editor automation workflows, and Unity 6.5 compatibility would be greatly appreciated.

### PR DESCRIPTION
**Pull request by akiojin**
## Summary

- Unity 6.5 で発生する7件の `Object.GetInstanceID()` CS0619 を解消し、Unity 2022.3 との互換性を維持します。
- Unity 6.4 以降の識別子を、全ビットを保持する十進文字列として返します。

## Changes

- `Editor/Helpers/ObjectIdentifier.cs`: バージョン分岐で native EntityId / int を取得し、modern ID を `EntityId.ToULong` から文字列化。
- `GameObjectHandler`、`SelectionHandler`、`ComponentHandler`、`SceneAnalysisHandler`: 6か所の応答 ID を共通ヘルパーに移行。
- `RuntimeChangeJournal`: 辞書キーを modern Unity では EntityId とし、ハッシュや int への切り詰めを回避。
- `Tests/Editor`: ID の安定性・復元・カルチャー非依存、ハンドラー間の整合性、記録復元を検証する8件の回帰テスト。
- `docs/tools.md`: JSON 型、識別子の有効期間、操作対象のパス指定を明記。
- `src/skills/runner.rs`: CI の Clippy 1.98 `question_mark` 指摘に対応し、既存の親ディレクトリ探索を同じ動作の `?` 式へ簡略化。

## Context

変更前のパッケージを隔離プロジェクトへ読み込み、Unity 6000.5.3f1 で Issue 記載どおり7件の CS0619 を再現しました。既存コードには修正が入っていなかったため、未達の互換性のみを対応しています。

## Testing

- [x] Unity 6000.5.3f1: コンパイル成功、EditMode 39/39 PASS。
- [x] Unity 6000.4.11f1: コンパイル成功、EditMode 39/39 PASS。
- [x] Unity 2022.3.62f3: コンパイル成功、EditMode 39/39 PASS。
- [x] `cargo +1.98.0 fmt --all -- --check`
- [x] `cargo +1.98.0 clippy --all-targets -- -D warnings`
- [x] `cargo +1.98.0 test skills::tests -- --test-threads=1`
- [x] `git diff --check`
- [x] `pnpm exec markdownlint docs/tools.md --config .markdownlint.json --ignore-path .markdownlintignore`

各 Unity 版の検証用プロジェクトに、このブランチのパッケージと対応する依存パッケージを読み込み、manifest の `testables` に `com.akiojin.unity-cli-bridge` を指定して実行:

```sh
"$UNITY_EDITOR" -batchmode -nographics -projectPath "$TEST_PROJECT" \
  -runTests -testPlatform EditMode \
  -testFilter 'UnityCliBridge.Tests.Editor.Helpers.ObjectIdentifierTests;UnityCliBridge.Tests.Editor.Helpers.RuntimeChangeJournalTests;UnityCliBridge.Tests.GameObjectHandlerTests;UnityCliBridge.Tests.ComponentHandlerTests' \
  -testResults "$RESULTS_XML" -logFile "$EDITOR_LOG"
```

検証対象は native ID の同一性、JSON 文字列から EntityId への復元、異なるカルチャー、create/find/modify/selection の ID 一致、初回スナップショット保持、別オブジェクトの独立復元、破棄済みオブジェクトの無視、復元後の再記録、既存 GameObject / Component 操作です。

Launch mode: autonomous

User Verification Result: n/a

Agent Visual Check: n/a (no UI surface)

## PR Readiness

- State: Draft
- Releaseable slice: yes — オブジェクト識別子の互換性修正と回帰テストで完結。
- Known blockers: canonical verify.run は別ワークスペースの共有検証枠を待機中。ローカル検証は3版とも39/39成功。
- Remaining acceptance: None

## Closing Issues

- Closes #231

## Related Issues / Links

- #231
- [Unity 6.4 EntityId implementation](https://github.com/Unity-Technologies/UnityCsReference/blob/6000.4/Runtime/Export/Scripting/UnityEngineObject.bindings.cs)

## Checklist

- [x] Tests added/updated
- [x] 変更に対応する検証と lint/format 成功（LSP・Web UI は未変更）
- [x] Documentation updated
- [x] Migration: modern Unity の `id` / `instanceId` は文字列として扱う。永続データ移行は不要。
- [x] CHANGELOG impact considered — コミットの BREAKING CHANGE footer に JSON 型変更を記載。

## Risk / Impact

- **Breaking change**: Unity 6.4 以降の `id` / `instanceId` が JSON number から string になります。旧 Unity の整数応答とフィールド名は維持します。操作対象は従来どおりパスで指定します。
- **Rollback**: このコミットを revert。ただし Unity 6.5 の元のコンパイルエラーが再発します。
- 既存の非推奨 API 警告は今回の範囲外です。Unity はエージェント側で準備・実行しており、人間による視認確認は主張していません。

### CODE REVIEW

**Comment by akiojin** [comment]
Progress
- 実装とローカル／CI検証は成功していますが、canonical verify.run の共有枠が期限超過した他 owner に保持され、正式記録を取得できないため Draft を維持します。

Done
- Unity 6000.5.3f1 / 6000.4.11f1 / 2022.3.62f3: 各39件 PASS。
- Rust 1.98 Clippy、スキル関連27件、CIに表示された9チェック: PASS。
- HEAD: 31f529f（Unity修正122282f + CI lint修正31f529f）。

Next
- PM が共有検証基盤を復旧後、登録済み検証行列を実行し、このPRをReadyにします。Unity環境のユーザー準備は不要です。
- gwt実行はblockedとして記録しました。期限超過lease: 4b20389a-f870-44f4-afea-c37a119ea7ff、holder PID21468 / gwt issue-4143。自分の待機PID22952のみ中断し、他の検証は停止していません。
- 復旧情報は Issue #231 と Board blocked entry dd9bc857-b998-4701-a692-c2f937e9afcf に記録済みです。
